[build-system]
requires = [
    "setuptools >= 65",
    "wheel >= 0.38,
]
build-backend = "setuptools.build_meta"

[project]
name = "api testing pytest"
dynamic = ["version"]
authors = [
    {name = "srajan", email = "srajanjain.rsg@gmail.com"}
]